# Generated by Django 4.0.5 on 2022-07-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
