# Generated by Django 4.0.5 on 2022-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('kindle', 'Kindle'), ('paperback', 'Paperback'), ('audiobook', 'Audiobook')], max_length=9)),
                ('category', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('is_in_stock', models.BooleanField()),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
